jwt:
  access:
    key: 7#70OZn0#Dsaodi98BK8C1%T&hBnrzgqK28o
    expiration-time: 86400000
  refresh:
    key: 7787dsa8dp7#%70OZ()BK8C1%Taskldjksal***
    expiration-time: 604800000
logging:
  file:
    name: transaction.log


spring:
  main:
    allow-circular-references: true