#add user
POST http://localhost:8090/api/auth/sign-up
Content-Type: application/json

{
  "phone": "+998946216666",
  "password": "Bekjon@03",
  "position": "Company"
}

###
#login
POST http://localhost:8090/api/auth/sign-in
Content-Type: application/json

{
  "phone": "+998946217575",
  "password": "Bekjon@03"
}


###
PUT http://localhost:8080/api/user/test_8b18ac05dcc6
Content-Type: application/json


###
GET http://localhost:8080/api/user/yopiq
Content-Type: application/json
###
POST http://localhost:8080/api/card/add
Content-Type: application/json

{
  "name": "test_c8d084103061",
  "cardNumber": "test_5182349c1048",
  "type": "test_4cd961acc28a",
  "currency": "test_ee2df24d6445"
}

###
POST http://localhost:8080/api/transaction/add

{
  "sender_card_number": "78146541212521478",
  "receiver_card_number": "78966541215521478",
  "sender_amount": 50,
  "receiver_amount": 50
}